import { Property } from './types';

export const COMPANY_INFO = {
  brandName: 'YEOBOLAND',
  legalName: 'PT. Yeoboland Alfazza Propertindo',
  whatsapp: '628999765777',
  whatsappDisplay: '0899-9765-777',
  email: 'yeobolandpropertindo@gmail.com',
  location: 'Bekasi & Sekitarnya, Indonesia',
};

export const PROPERTY_TYPES = [
  'Semua',
  'Rumah',
  'Ruko',
  'Tanah',
  'Villa',
  'Gudang',
  'Apartemen',
];

const getImg = (id: number, width = 1000, height = 800) => 
  `https://picsum.photos/id/${id}/${width}/${height}`;

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Mahakarya Modern Grand Wisata',
    slug: 'rumah-modern-grand-wisata',
    price: 1500000000,
    location: 'Grand Wisata, Bekasi',
    type: 'Rumah',
    transactionType: 'Di Jual',
    description: 'Sebuah hunian modern minimalis yang memukau di kawasan prestisius Grand Wisata. Properti ini dirancang dengan sirkulasi udara sempurna, langit-langit tinggi, dan material premium. Siap huni dan dekat dengan akses tol serta pusat perbelanjaan.',
    specs: {
      landSize: 120,
      buildingSize: 90,
      bedrooms: 3,
      bathrooms: 2,
      certificate: 'SHM',
      electricity: 2200,
      furnishing: 'Semi-Furnished',
      yearBuilt: 2022,
    },
    images: [getImg(10), getImg(11), getImg(12)],
    isFeatured: true,
    createdAt: '2023-10-01',
  },
  {
    id: '2',
    title: 'Ruko Strategis Pusat Bisnis Bekasi',
    slug: 'ruko-strategis-bekasi-timur',
    price: 2100000000,
    location: 'Bekasi Timur',
    type: 'Ruko',
    transactionType: 'Di Jual',
    description: 'Lokasi emas untuk bisnis Anda. Ruko ini terletak di jalan utama dengan trafik padat 24 jam. Sangat cocok untuk kantor, bank, atau retail. Parkir luas dan struktur bangunan kokoh.',
    specs: {
      landSize: 60,
      buildingSize: 110,
      bedrooms: 1,
      bathrooms: 2,
      floors: 2,
      certificate: 'HGB',
      electricity: 3500,
      furnishing: 'Non-Furnished',
    },
    images: [getImg(20), getImg(21), getImg(22)],
    createdAt: '2023-09-15',
  },
  {
    id: '3',
    title: 'Villa Eksklusif Nuansa Bali',
    slug: 'villa-mewah-sentul',
    price: 3500000000,
    location: 'Sentul City',
    type: 'Villa',
    transactionType: 'Di Jual',
    description: 'Lepaskan penat di Villa berkonsep resort ini. Dilengkapi private pool, taman tropis, dan interior mewah. Pemandangan gunung yang asri menjadikannya investasi gaya hidup terbaik.',
    specs: {
      landSize: 300,
      buildingSize: 250,
      bedrooms: 4,
      bathrooms: 4,
      certificate: 'SHM',
      electricity: 5500,
      furnishing: 'Full Furnished',
    },
    images: [getImg(30), getImg(31), getImg(32)],
    isFeatured: true,
    createdAt: '2023-10-05',
  },
  {
    id: '4',
    title: 'Gudang Industri Akses Kontainer',
    slug: 'gudang-industri-cikarang',
    price: 150000000, // Rent per year
    location: 'Kawasan Industri Cikarang',
    type: 'Gudang',
    transactionType: 'Di Sewakan',
    description: 'Gudang high-ceiling standar internasional. Lantai beton bertulang, loading dock luas, akses kontainer 40ft, dan keamanan 24 jam. Siap operasional.',
    specs: {
      landSize: 1000,
      buildingSize: 800,
      bedrooms: 0,
      bathrooms: 2,
      certificate: 'HGB',
      electricity: 11000,
      furnishing: 'Non-Furnished',
    },
    images: [getImg(40), getImg(41)],
    createdAt: '2023-08-20',
  },
  {
    id: '5',
    title: 'Hunian Keluarga Muda Harapan Indah',
    slug: 'rumah-keluarga-harapan-indah',
    price: 850000000,
    location: 'Harapan Indah, Bekasi',
    type: 'Rumah',
    transactionType: 'Di Jual',
    description: 'Pilihan cerdas untuk keluarga muda. Cluster bebas banjir dengan sistem satu pintu. Lingkungan asri, dekat sekolah, pasar modern, dan fasilitas kuliner.',
    specs: {
      landSize: 72,
      buildingSize: 45,
      bedrooms: 2,
      bathrooms: 1,
      certificate: 'SHM',
      electricity: 1300,
      furnishing: 'Non-Furnished',
    },
    images: [getImg(50), getImg(51)],
    createdAt: '2023-10-10',
  },
  {
    id: '6',
    title: 'Tanah Kavling Investasi Tinggi',
    slug: 'tanah-kavling-jatiasih',
    price: 500000000, 
    location: 'Jatiasih, Bekasi',
    type: 'Tanah',
    transactionType: 'Di Jual',
    description: 'Tanah siap bangun di area berkembang pesat. Bentuk kotak proporsional, kontur datar. Sangat ideal untuk dibangun mini cluster atau rumah tinggal pribadi yang luas.',
    specs: {
      landSize: 100,
      buildingSize: 0,
      bedrooms: 0,
      bathrooms: 0,
      certificate: 'SHM',
      electricity: 0,
      furnishing: 'Non-Furnished',
    },
    images: [getImg(60)],
    createdAt: '2023-09-01',
  },
];